name = "NGRefTools"
uuid = "1b89f441-c1fd-4480-9e82-cf849a5cdb22"
authors = ["Michael Mattocks <mike.mattocks@utoronto.ca>"]
version = "0.1.1"

[deps]
ConjugatePriors = "1624bea9-42b1-5fc1-afd3-e96f729c8d6c"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
